model:
  base_learning_rate: 1.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: patch
    image_size: 64
    channels: 3
    cond_stage_trainable: false
    conditioning_key: hybrid
    use_ema: false
    monitor: val/loss_simple_ema
    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [10000]
        cycle_lengths: [10000000000000]
        f_start: [1.e-6]
        f_max: [1]
        f_min: [1]
    unet_config:
      target: ldm.modules.diffusionmodules.imagenmodel.EfficientUNetModel
      params:
        in_channels: 7
        out_channels: 3
        model_channels: 256
        attention_resolutions: [4, 8]
        num_res_blocks: [2, 2, 2, 2]
        channel_mult: [1, 2, 3, 4]
        num_heads: 8
        resblock_updown: true
        context_dim: 512
        transformer_depth: 1
        checkpoint: deepspeed
        precision: 16
    first_stage_config:
      target: ldm.models.autoencoder.IdentityFirstStage
    cond_stage_config:
      target: ldm.modules.encoders.modules.ClipPatchEmbedder
      params:
        clip_model_name: ViT-B/32
        cond_dropout: 0.4
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 128
    num_workers: 32
    train:
      target: ldm.data.imagenet.ImageNetPatchInpaintTrain
      params:
        size: 64
        min_patch_f: 0.3
        max_patch_f: 0.7
        min_crop_f: 0.5
        max_crop_f: 1.0
        random_crop: true
        clip_model_name: ViT-B/32
    validation:
      target: ldm.data.imagenet.ImageNetPatchInpaintValidation
      params:
        size: 64
        min_patch_f: 0.3
        max_patch_f: 0.7
        min_crop_f: 0.5
        max_crop_f: 1.0
        random_crop: true
        clip_model_name: ViT-B/32
lightning:
  trainer:
    benchmark: True
    max_epochs: -1
    find_unused_parameters: false
    precision: 16
    strategy: deepspeed_stage_3_offload