model:
  base_learning_rate: 1.0e-04
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l2
    first_stage_key: image
    cond_stage_key: lr_image
    image_size: 128
    channels: 3
    concat_mode: true
    cond_stage_trainable: false
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
          image_size: 128
          in_channels: 6
          out_channels: 3
          model_channels: 192
          attention_resolutions: [16, 8]
          num_res_blocks: 2
          channel_mult: [1, 2, 2, 4]
          num_head_channels: 32
          use_spatial_transformer: true
          context_dim: 512
    first_stage_config:
      target: ldm.models.autoencoder.IdentityFirstStage
    cond_stage_config:
      target: torch.nn.Identity
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 32
    wrap: false
    num_workers: 32
    train:
      target: ldm.data.avid.AvidSuperResTrain
      params:
        size: 512
        degradation: bsrgan_light
        downscale_f: 4
        min_crop_f: 0.5
        max_crop_f: 1.0
    validation:
      target: ldm.data.avid.AvidSuperResValidation
      params:
        size: 512
        degradation: bsrgan_light
        downscale_f: 4
        min_crop_f: 0.5
        max_crop_f: 1.0
lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 2500
        increase_log_steps: false
        max_images: 8
        clamp: true
        log_images_kwargs:
          plot_diffusion_rows: true
          plot_progressive_rows: false
          inpaint: false
  trainer:
    benchmark: True
    max_epochs: -1
    precision: 16
    strategy: fsdp_native