model:
  base_learning_rate: 1.0e-07
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    beta_schedule: cosine
    # original_elbo_weight: 0.001
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    image_size: 64
    channels: 3
    cond_stage_trainable: false
    use_ema: true
    monitor: val/loss_simple_ema
    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [10000]
        cycle_lengths: [10000000000000]
        f_start: [1.e-7]
        f_max: [1]
        f_min: [1]
    unet_config:
      target: ldm.modules.diffusionmodules.imagenmodel.EfficientUNetModel
      params:
        in_channels: 3
        out_channels: 3
        model_channels: 256
        attention_resolutions: [4, 8]
        num_res_blocks: [2, 2, 2, 2]
        channel_mult: [1, 2, 3, 4]
        num_heads: 8
        resblock_updown: true
        transformer_depth: 1
        checkpoint: fairscale
        precision: 16
        skip_rescale: false
    first_stage_config:
      target: ldm.models.autoencoder.IdentityFirstStage
    cond_stage_config: __is_unconditional__
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 64
    num_workers: 36
    train:
      target: ldm.data.imagenet.ImageNetTrain
      params:
        config:
          size: 64
    validation:
      target: ldm.data.imagenet.ImageNetValidation
      params:
        config:
          size: 64
lightning:
  trainer:
    benchmark: true
    max_epochs: -1
    find_unused_parameters: false
    precision: 16
    strategy: ddp_fully_sharded‘